const actions = {
  ADD_USER: "ADD_USER",
  REMOVE_USER: "REMOVE_USER",
  UPDATE_USER_DETAILS: "UPDATE_USER_DETAILS",
  ADD_TO_RECEPIENTS_ARRAY: "ADD_TO_RECEPIENTS_ARRAY",
  REMOVE_FROM_RECEPIENTS_ARRAY: "REMOVE_FROM_RECEPIENTS_ARRAY",
  ADD_RECEPIENT: "ADD_RECEPIENT",
  REMOVE_ONERECEPIENT: "REMOVE_ONERECEPIENT",
  REMOVE_ALLRECEPIENTS: "REMOVE_ALLRECEPIENTS",
  UPDATE_RECEPIENT_DETAILS: "UPDATE_RECEPIENT_DETAILS",
  SET_ACTIVE_RECEPIENT: "SET_ACTIVE_RECEPIENT",
  REMOVE_ACTIVE_RECEPIENT: "REMOVE_ACTIVE_RECEPIENT",
  ADD_TRANSACTION: "ADD_TRANSACTION",
  REMOVE_TRANSACTION: "REMOVE_TRANSACTION",
  UPDATE_RECEPIENT_AMOUNT: "UPDATE_RECEPIENT_AMOUNT",
  UPDATE_USER_AMOUNT: "UPDATE_USER_AMOUNT",
  SET_DELETION_PASSWORD: "SET_DELETION_PASSWORD",
  ADD_REMINDER: "ADD_REMINDER",
  REMOVE_REMINDER: "REMOVE_REMINDER",

  TOGLLE_UPDATE: "TOGLLE_UPDATE",
};

export default actions;
